baseURL = "https://lmtreser.github.io/"
languageCode = "es"
title = "Lucas Martín Treser"
theme = "hugo-theme-mini"
defaultContentLanguage = "es"
hasCJKLanguage = true
# paginate = 3

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Lucas Martin Treser"
bio = "EN CONSTRUCCIÓN"
description = "Acerca de..."
enableRSS = false
enableComments = false
enableGoogleAnalytics = false
showToc = false
showPowerBy = false
math = false
hiddenPostSummaryInHomePage = false
copyright = "[Blog](https://www.automatismos-mdq.com.ar) · [GitHub](https://github.com/lmtreser) · [GitLab](https://gitlab.com/lmtreser) · [Mastodon](https://mastodon.online/@lmtreser)"

[[params.links]]
name = "Código fuente"
path = "https://github.com/lmtreser/hugo-static-sites/tree/main/about_me"