baseURL = "https://lmtreser.github.io/"
languageCode = "es"
title = "Lucas Martín Treser"
theme = "hugo-theme-mini"
defaultContentLanguage = "es"
hasCJKLanguage = true

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Lucas Martin Treser"
bio = "Técnico Electrónico"
description = "My Blog"
enableRSS = false
enableComments = false
enableGoogleAnalytics = false
showToc = false
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = "© Copyright 2024 💙 lmtreser"